version: '3.4'

services:

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: elasticsearch1
    environment:
      - node.name=elasticsearch1
      - cluster.name=gutenberg-cluster
      - discovery.seed_hosts=172.19.0.2,172.19.0.3,172.19.0.4
      - cluster.initial_master_nodes=172.19.0.2,172.19.0.3,172.19.0.4
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      esnet:
        ipv4_address: 172.19.0.2

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: elasticsearch2
    environment:
      - node.name=elasticsearch2
      - cluster.name=gutenberg-cluster
      - discovery.seed_hosts=172.19.0.2,172.19.0.3,172.19.0.4
      - cluster.initial_master_nodes=172.19.0.2,172.19.0.3,172.19.0.4
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    #ports:
    #  - 9200:9200
    networks:
      esnet:
        ipv4_address: 172.19.0.3

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: elasticsearch3
    environment:
      - node.name=elasticsearch3
      - cluster.name=gutenberg-cluster
      - discovery.seed_hosts=172.19.0.2,172.19.0.3,172.19.0.4
      - cluster.initial_master_nodes=172.19.0.2,172.19.0.3,172.19.0.4
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    #ports:
    #  - 9200:9200
    networks:
      esnet:
        ipv4_address: 172.19.0.4 

volumes:
  esdata1:
    external:
      name: gutenberg-es-data1
  esdata2:
    external:
      name: gutenberg-es-data2
  esdata3:
    external:
      name: gutenberg-es-data3
  esdata4:
    external:
      name: gutenberg-es-data4
  esdata5:
    external:
      name: gutenberg-es-data5

networks:
  esnet:
    external:
      name: gutenberg

    
                
            



